#  Array Sorting and Filtering 

In [1]:
# Import needed libraries

import numpy as np

In [2]:
list1 = [[12, 34, 56], [12, 13, 8,], [6, 5, 10]]

# Create array of list above
array = np.array(list1)
array

array([[12, 34, 56],
       [12, 13,  8],
       [ 6,  5, 10]])

In [3]:
# Sort array by column
sorted_array = np.sort(array,axis=1)
sorted_array

array([[12, 34, 56],
       [ 8, 12, 13],
       [ 5,  6, 10]])

In [4]:
 # Slice of array
slice_array = np.array([sorted_array[1,0],
                        sorted_array[1,1],
                        sorted_array[0,2]])
slice_array

array([ 8, 12, 56])

In [5]:
# Create array random integers

rng = np.random.default_rng(seed=42)
array = rng.integers(low=-100,high=100,size=(3,3))
array

array([[-83,  54,  30],
       [-13, -14,  71],
       [-83,  39, -60]], dtype=int64)

In [6]:
#Replace negative values with 0

array = np.where(array < 0,0,array)
array

array([[ 0, 54, 30],
       [ 0,  0, 71],
       [ 0, 39,  0]], dtype=int64)

In [7]:
list1 = [[12, 23, 34, 34], [13, 13, 20, 21]]

# Create array of list above
array = np.array(list1)
array

array([[12, 23, 34, 34],
       [13, 13, 20, 21]])

In [8]:
# Unique values within array

unique_elements, element_count = np.unique(array, return_counts=True)
print('Unique elements:', unique_elements)
print('Element count:', element_count)

Unique elements: [12 13 20 21 23 34]
Element count: [1 2 1 1 1 2]


In [9]:
# Flatten array

array = array.flatten()
array

array([12, 23, 34, 34, 13, 13, 20, 21])