#  Essentials of NumPy, Pandas, and Matplotlib

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lst = [1,2,3,4,5,6]

# Create array from list
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
# Create array of floats from list

arr = np.array(lst, dtype=float)
arr

array([1., 2., 3., 4., 5., 6.])

In [4]:
names = [['Jon', 'Mary', 'Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)
arr1


array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [5]:
# Dimension of array
arr1.ndim

2

In [6]:
# Array of arange
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
# Array of zeros
arr3 = np.zeros((2,3), dtype=float)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Array of ones
arr4 = np.ones((2,3), dtype=float)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create a random number generator
rng = np.random.default_rng()

# Array of random integers from 0 to 9
array = rng.integers(low=0,high=10,size=(2,4))
array

array([[6, 5, 1, 4],
       [8, 7, 4, 5]], dtype=int64)

In [10]:
# Create a random number generator
rng = np.random.default_rng(seed=42)

# Array of random floats between 0 and 1
array = rng.random((2,4))
array

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431]])

##  Accessing Array Elements

In [11]:
names = [['Jon', 'Mary', 'Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)
arr1

array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [12]:
# Select Mary and Paul
mary_paul = arr1[0,1:]
mary_paul

array(['Mary', 'Paul'], dtype='<U5')

In [13]:
# Creating an element indices
select_peter = np.array([1,0])
select_paul = np.array([0,-1])

select_peter_paul = arr1[select_paul,select_peter]
select_peter_paul

array(['Mary', 'Peter'], dtype='<U5')

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Create a boolean mask
filter_array = arr % 2 != 0

# Select from array
arr[filter_array]

array([1, 3, 5, 7, 9])

In [15]:
# Create an array
arr = np.array([[1,2,3],[4,5,6],[7,8,9 ]])

# Flatten the array using reshape function
np.reshape(arr, 9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Create array 
names = [['Jon','Mary','Paul'],['Peter','Ben','Saul']]

arr1 = np.array(names)
arr1

array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [17]:
# Reshape the array to (3,2)
new_arr = np.reshape(arr1,(3,2))
new_arr

array([['Jon', 'Mary'],
       ['Paul', 'Peter'],
       ['Ben', 'Saul']], dtype='<U5')

In [18]:
# Create two arrays
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

arr3 = np.concatenate((arr1, arr2),axis=0)
arr3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 150]])

In [19]:
# Create array 
names = [['Jon','Mary','Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)

# Split arrays into two arrays
split_1,split_2 = np.split(arr1,2)

In [20]:
split_1

array([['Jon', 'Mary', 'Paul']], dtype='<U5')

In [21]:
split_2

array([['Peter', 'Ben', 'Saul']], dtype='<U5')

In [22]:
# Create two arrays
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

# Dot product of a
# np.dot(arr1, arr2)

In [23]:
# Dot product of two arrays with one transposed
np.dot(arr1, arr2.transpose())

array([[ 6800,  8600],
       [16700, 21200],
       [26600, 33800]])

##  Mathematical Functions 

In [24]:
# Create two arrays
arr1 = np.array([[1,2,4], [6,7,8]])
arr2 = np.array([[3,3,6],[4,5,7]])

# Add two arrays
np.add(arr1, arr2)

array([[ 4,  5, 10],
       [10, 12, 15]])

In [25]:
# Substract the arrays

np.subtract(arr1, arr2)

array([[-2, -1, -2],
       [ 2,  2,  1]])

In [26]:
# Multiply the arrays
np.multiply(arr1, arr2)

array([[ 3,  6, 24],
       [24, 35, 56]])

In [27]:
# Divide the arrays
np.divide(arr1, arr2)

array([[0.33333333, 0.66666667, 0.66666667],
       [1.5       , 1.4       , 1.14285714]])

In [28]:
# Raise array to the power of 2
np.power(arr2, 2)

array([[ 9,  9, 36],
       [16, 25, 49]], dtype=int32)

In [29]:
# Square root the array
np.sqrt(arr2)

array([[1.73205081, 1.73205081, 2.44948974],
       [2.        , 2.23606798, 2.64575131]])

##  Statistical Functions

In [30]:
# Create array
arr = np.array([[3,3,6],[4,5,7]])

arr

array([[3, 3, 6],
       [4, 5, 7]])

In [31]:
# Compute mean each row
np.mean(arr,axis=1)

array([4.        , 5.33333333])

In [32]:
# Compute mean each column
np.mean(arr,axis=0)

array([3.5, 4. , 6.5])

In [33]:
# Compute median
np.median(arr,axis=1)

array([3., 5.])

In [34]:
# Compute standard deviation
np.std(arr,axis=0)

array([0.5, 1. , 0.5])

In [35]:
# Compute variance
np.var(arr,axis=0)

array([0.25, 1.  , 0.25])

In [36]:
# Compute minimum value 0f each column
np.min(arr,axis=0)

array([3, 3, 6])

In [37]:
# Compute maximum value whole array
np.max(arr,axis=None)

7

## Pandas Series

In [38]:
# Create a Pandas Series
fruits = pd.Series(['Orange', 'Apple', 'Mango'], name='Friuts')
fruits


0    Orange
1     Apple
2     Mango
Name: Friuts, dtype: object

In [39]:
# Pandas Series with index

fruits = pd.Series(['Orange', 'Apple', 'Mango'],
                   name='Friuts',
                   index=['a', 'b', 'c'])
fruits

a    Orange
b     Apple
c     Mango
Name: Friuts, dtype: object

In [40]:
# Pandas Series of integers
int_num = pd.Series([10,20,30],name='numbers')
int_num

0    10
1    20
2    30
Name: numbers, dtype: int64

In [41]:
# Pandas Series with mixed dtype
mixed_dtype = pd.Series([10,20,30,'Orange'],name='mixed')
mixed_dtype

0        10
1        20
2        30
3    Orange
Name: mixed, dtype: object

In [42]:
# OR
mixed_dtype = pd.Series([10,20,30,14.5],name='mixed')
mixed_dtype

0    10.0
1    20.0
2    30.0
3    14.5
Name: mixed, dtype: float64

In [43]:
# Pandas Series with specified dtype
int_num = pd.Series([10,20,30],
                    name='numbers',
                    dtype='int8'
                    )
int_num

0    10
1    20
2    30
Name: numbers, dtype: int8

In [45]:
# Create Pandas Series

num_series = pd.Series([10,20,30,40],name='numbers')
num_series

0    10
1    20
2    30
3    40
Name: numbers, dtype: int64

In [46]:
# Change dtype of Pandas Series
num_series = num_series.astype('float')
num_series

0    10.0
1    20.0
2    30.0
3    40.0
Name: numbers, dtype: float64