#  Essentials of NumPy, Pandas, and Matplotlib

In [1]:
# Import necessary libraries
import numpy as np

In [2]:
lst = [1,2,3,4,5,6]

# Create array from list
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
# Create array of floats from list

arr = np.array(lst, dtype=float)
arr

array([1., 2., 3., 4., 5., 6.])

In [4]:
names = [['Jon', 'Mary', 'Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)
arr1


array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [5]:
# Dimension of array
arr1.ndim

2

In [6]:
# Array of arange
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
# Array of zeros
arr3 = np.zeros((2,3), dtype=float)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Array of ones
arr4 = np.ones((2,3), dtype=float)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create a random number generator
rng = np.random.default_rng()

# Array of random integers from 0 to 9
array = rng.integers(low=0,high=10,size=(2,4))
array

array([[8, 0, 3, 0],
       [4, 6, 5, 6]], dtype=int64)

In [10]:
# Create a random number generator
rng = np.random.default_rng(seed=42)

# Array of random floats between 0 and 1
array = rng.random((2,4))
array

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431]])

##  Accessing Array Elements

In [11]:
names = [['Jon', 'Mary', 'Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)
arr1

array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [12]:
# Select Mary and Paul
mary_paul = arr1[0,1:]
mary_paul

array(['Mary', 'Paul'], dtype='<U5')

In [13]:
# Creating an element indices
select_peter = np.array([1,0])
select_paul = np.array([0,-1])

select_peter_paul = arr1[select_paul,select_peter]
select_peter_paul

array(['Mary', 'Peter'], dtype='<U5')

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Create a boolean mask
filter_array = arr % 2 != 0

# Select from array
arr[filter_array]

array([1, 3, 5, 7, 9])

In [15]:
# Create an array
arr = np.array([[1,2,3],[4,5,6],[7,8,9 ]])

# Flatten the array using reshape function
np.reshape(arr, 9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Create array 
names = [['Jon','Mary','Paul'],['Peter','Ben','Saul']]

arr1 = np.array(names)
arr1

array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [17]:
# Reshape the array to (3,2)
new_arr = np.reshape(arr1,(3,2))
new_arr

array([['Jon', 'Mary'],
       ['Paul', 'Peter'],
       ['Ben', 'Saul']], dtype='<U5')

In [18]:
# Create two arrays
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

arr3 = np.concatenate((arr1, arr2),axis=0)
arr3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 150]])

In [19]:
# Create array 
names = [['Jon','Mary','Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)

# Split arrays into two arrays
split_1,split_2 = np.split(arr1,2)

In [20]:
split_1

array([['Jon', 'Mary', 'Paul']], dtype='<U5')

In [21]:
split_2

array([['Peter', 'Ben', 'Saul']], dtype='<U5')

In [23]:
# Create two arrays
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

# Dot product of a
# np.dot(arr1, arr2)

In [24]:
# Dot product of two arrays with one transposed
np.dot(arr1, arr2.transpose())

array([[ 6800,  8600],
       [16700, 21200],
       [26600, 33800]])