#  Essentials of NumPy, Pandas, and Matplotlib

In [3]:
# Import necessary libraries
import numpy as np

In [4]:
lst = [1,2,3,4,5,6]

# Create array from list
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
# Create array of floats from list

arr = np.array(lst, dtype=float)
arr

array([1., 2., 3., 4., 5., 6.])

In [6]:
names = [['Jon', 'Mary', 'Paul'],['Peter','Ben','Saul']]
arr1 = np.array(names)
arr1


array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [7]:
# Dimension of array
arr1.ndim

2

In [8]:
# Array of arange
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# Array of zeros
arr3 = np.zeros((2,3), dtype=float)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Array of ones
arr4 = np.ones((2,3), dtype=float)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Create a random number generator
rng = np.random.default_rng()

# Array of random integers from 0 to 9
array = rng.integers(low=0,high=10,size=(2,4))
array

array([[8, 6, 3, 5],
       [8, 8, 5, 6]], dtype=int64)

In [12]:
# Create a random number generator
rng = np.random.default_rng(seed=42)

# Array of random floats between 0 and 1
array = rng.random((2,4))
array

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431]])