# Day 2 - Creating and Manipulating Arrays

In [1]:
# Importing NumPy
import numpy as np

In [2]:
# Checking version of NumPy
np.__version__

'1.26.0'

In [3]:
lilist1 = [2, 3, 4, 6]

# Creating a one-dimensional array
array = np.array(lilist1)
array 

array([2, 3, 4, 6])

In [4]:
array.shape

(4,)

In [5]:
# Function takes array and returns array reversed
def array_reversed(array):
    return array[::-1]

In [6]:
# Reverse the array using array_reversed
reversed_array = array_reversed(array)
reversed_array

array([6, 4, 3, 2])

In [7]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

# Creating array with lists above
array1 = np.array([list1, list2])
array1


array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [8]:
# Checking shape, dimensions, and datatype of array
array1.shape

(2, 4)

In [9]:
array1.ndim

2

In [10]:
array1.dtype

dtype('int32')

In [11]:
# Check size of array
array_size = np.size(array1)
print(f'Size of array1 is {array_size}')

Size of array1 is 8


In [12]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

# Creating array with lists above
array2 = np.array([list1, list2, list3])
array2


array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [13]:
# Create an array with int64 data type
array2 = array2.astype('int64')
array2

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]], dtype=int64)

### Array only have elements of a single data type.