# Array Creation and Vector Operations 

In [1]:
# Importing needed libraries

import numpy as np

In [2]:
list_numbers = [[12, 23, -45], [18, -77, -44]]

# Creating arrays from the list
array = np.array(list_numbers)
array

array([[ 12,  23, -45],
       [ 18, -77, -44]])

In [3]:
# Retrieve negative numbers

neg_numbers = np.where(array < 0)
print(array[neg_numbers])

[-45 -77 -44]


In [4]:
# Array by 2

array_by_2 = array * 2
print(array_by_2)

[[  24   46  -90]
 [  36 -154  -88]]


In [5]:
# OR

array_by_2 = np.multiply(array,2)
print(array_by_2)

[[  24   46  -90]
 [  36 -154  -88]]


In [6]:
# Sum of numbers on axis 1
sum_on_axis1 = np.sum(array_by_2,axis=1)
sum_on_axis1

array([ -20, -206])

In [7]:
# Sum of numbers on axis 0
sum_on_axis0 = np.sum(array_by_2,axis=0)
sum_on_axis0

array([  60, -108, -178])

In [8]:
# Create array with arange function

array1 = np.arange(100).reshape(2,5,10)
array1

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [9]:
# Slice array

array1[1,0,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
array_row_one = array[0]
array_row_two = array[1]

# Greater function
greater_num = np.greater(array_row_one, array_row_two)

print(f'Numbers in row 1 greater than those in row 2 is/are {sum(greater_num)}')

Numbers in row 1 greater than those in row 2 is/are 1
