#  Array Manipulation and Vector Operations

In [1]:
# Impoting the needed libraries

import numpy as np
import matplotlib.pyplot as plt

In [2]:
list_str = ["23", "12", "90", "28", "30"]

# Create array from the list above
array = np.array(list_str)
array = array

In [4]:
# Calculate the std of the array
array = array.astype('int')
np.std(array)

27.419700946582186

In [5]:
# Convert the array data type to float

array1 = array.astype('float32')
array1

array([23., 12., 90., 28., 30.], dtype=float32)

In [6]:
lst =  [90.0, 28.0, 30.0]

# Create array from the list above
array2 = np.array(lst)
array2

array([90., 28., 30.])

In [7]:
# Calculate the sum of the array
np.sum(array2)

148.0

In [10]:
# Create an array of random values
rng = np.random.default_rng(seed=42)
array = rng.integers(low=0,high=100,size=(5,5))
array

array([[ 8, 77, 65, 43, 43],
       [85,  8, 69, 20,  9],
       [52, 97, 73, 76, 71],
       [78, 51, 12, 83, 45],
       [50, 37, 18, 92, 78]], dtype=int64)

In [11]:
# Shape of the array
array.shape

(5, 5)

In [13]:
# Minimum and maximum values of the array

mini = array.min()
maxi = array.max()
print(f"The minimum and maximum values of the array are {mini} and {maxi} respectively")

The minimum and maximum values of the array are 8 and 97 respectively


In [15]:
mean = array.mean()
std = array.std()
print(f'The mean of the array is {mean}')
print(f'The Standard deviation of the array is {std.round(2)}')

The mean of the array is 53.6
The Standard deviation of the array is 27.83


In [20]:
first_names = ["John", " Kenny"]
last_names = ["Smith", "Sakula"]

# Join the two lists

array = np.char.join("",[first_names, last_names])
array = array.astype('U6')
array

array([['John', ' Kenny'],
       ['Smith', 'Sakula']], dtype='<U6')

In [22]:
array1 = array[:,0]
array2 = array[:,1]

array1, array2

(array(['John', 'Smith'], dtype='<U6'),
 array([' Kenny', 'Sakula'], dtype='<U6'))