# Slicing NumPy Arrays

In [1]:
# Import NumPy

import numpy as np

In [5]:
# Create one-dimensional array

rng = np.random.default_rng(seed=42)
array = rng.integers(0,21,size=10)
array

array([ 1, 16, 13,  9,  9, 18,  1, 14,  4,  1], dtype=int64)

In [7]:
# Slice indexes 2,4 and 7 from array

array_slice = array[[2,4,7]]
array_slice


array([13,  9, 14], dtype=int64)

In [8]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], 
 [11, 12, 13, 14, 15]] 

# Create array with list above
array1 = np.array(my_list)
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
# Check shape of array

array1.shape

(3, 5)

In [10]:
# Slice of array of 3,8,13
array_slice = array1[:,2]
array_slice

array([ 3,  8, 13])

In [11]:
lis1 = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], 
 [11, 12, 13, 14, 15]]]

# Create 3d-dimensional array with list above

array_3d = np.array(lis1)
array_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [14]:
# Slice 3d-dimensional array

array_slice = array_3d[0,0,3], array_3d[0,1,2], array_3d[0,2,-1]
print(np.array(array_slice))

[ 4  8 15]
